/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tv.xeeng.dataLayer;

public class ShoutBoxJNI {
	public final static native int shoutbox_gen_hash(String jarg1,
			String jarg2, String jarg3, byte[] jarg4);
}
